#!/bin/bash

if [ -z "$AI_COMMIT_MESSAGE_USE_TMP" ]; then
    CLIPBOARD_CONTENT=$(pbpaste)
else
    CLIPBOARD_CONTENT=$(cat "${HOME}/.tmp/commit-message.txt")
fi

if [ -z "$CLIPBOARD_CONTENT" ]; then
  echo "Error: Clipboard is empty. Please copy a commit message to the clipboard."
  exit 1
fi

echo "Committing with message from clipboard:"
echo ""
echo "$CLIPBOARD_CONTENT"
echo ""
git commit -m "$CLIPBOARD_CONTENT"

if [ -z "$AI_COMMIT_MESSAGE_USE_TMP" ]; then
    pbcopy < /dev/null
else
    rm "${HOME}/.tmp/commit-message.txt"
fi
echo ""
echo "✅ Commit successful."
